# Task 1:

1.
Write a function to compute 5/0 and use try/except to catch the exceptions.


In [2]:
try :
    a = 5/0
except ZeroDivisionError as e:
    print(e)

division by zero


2. Implement a Python program to generate all sentences where subject is in ["Americans",
    "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

In [4]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in [i+' '+j+' '+k+'.'for i in subjects for j in verbs for k in objects]:
    print(i)

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2:

Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [21]:
import numpy as np

def aVandermonde(l, N, increasing = False):
    if increasing:
        print(np.array([ j** i for j in l for i in range(N)]).reshape(len(l), N))
    else:
        print(np.array([ j** (N-1-i) for j in l for i in range(N)]).reshape(len(l), N))
        
mylst = [1,2,3]
N = 4
print('with decreasing ')
print('-'*50)
aVandermonde(np.array(mylst),N)
print('with increasing ')
print('-'*50)
aVandermonde(np.array(mylst),N, increasing= True)

with decreasing 
--------------------------------------------------
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]
with increasing 
--------------------------------------------------
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]
